name: whatsapp_flutter_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.16
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.10+1
  flutter_contacts: ^1.1.5+1
  uuid: ^4.3.3
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  giphy_get: ^3.5.4
  emoji_picker_flutter: ^2.0.0
  camera: ^0.10.1
  path_provider: ^2.0.11
  image_picker: ^1.0.7
  video_player: ^2.4.9
  shimmer: ^3.0.0
  agora_uikit: ^1.1.0
  audio_waveforms: ^1.0.4
  cached_video_player: ^2.0.3
  audioplayers: ^5.2.1
  swipe_to: ^1.0.2
  sms_autofill: ^2.2.0
  image_cropper: ^5.0.1

  firebase_auth: ^4.2.5
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  extended_image: ^8.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
