// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0_e51NJEFnNUMH5mq9d3ABDfkwbmNnw',
    appId: '1:1053507259492:web:0f177bb964cad12528e371',
    messagingSenderId: '1053507259492',
    projectId: 'test-44046',
    authDomain: 'test-44046.firebaseapp.com',
    databaseURL: 'https://test-44046.firebaseio.com',
    storageBucket: 'test-44046.appspot.com',
    measurementId: 'G-L966QG42PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCQtETZHZeu002MkaVgmskqzYuq7KB9s',
    appId: '1:1053507259492:android:eda7ff95e8afed3528e371',
    messagingSenderId: '1053507259492',
    projectId: 'test-44046',
    databaseURL: 'https://test-44046.firebaseio.com',
    storageBucket: 'test-44046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApoxRItP-iCdwGTdXIsfBa8LwIiPH0JGw',
    appId: '1:1053507259492:ios:2072798b482e1e3a28e371',
    messagingSenderId: '1053507259492',
    projectId: 'test-44046',
    databaseURL: 'https://test-44046.firebaseio.com',
    storageBucket: 'test-44046.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApoxRItP-iCdwGTdXIsfBa8LwIiPH0JGw',
    appId: '1:1053507259492:ios:6ecc9cea6f4ff7c728e371',
    messagingSenderId: '1053507259492',
    projectId: 'test-44046',
    databaseURL: 'https://test-44046.firebaseio.com',
    storageBucket: 'test-44046.appspot.com',
    iosBundleId: 'com.example.whatsappclone.RunnerTests',
  );
}
